### ISSUE TITLE
Virtual function are not autocompleted and are showing warnings

### ISSUE THREAD

**Issue by KasparRosin** [phpactor/phpactor#1557]
Hey, 

I read throw some of the issues and to my understanding, this should already be implemented in [#51](https://github.com/phpactor/worse-reflection/pull/51)?
Currently, the `@property` magic variables are auto-completed, but `@method` is not and are showing warnings `Method "name" does not exist` for me.
Working with the same [Laravel Faker](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Generator.php) class mentioned in #682

Currently working with latest master commit version: `af0d2ef `.
IDE is nvim, with nvim-lspconfig and nvim-lsp-installer.

Let me know if i can provide any additional information. 

Edit:
The warnings only appear after executing write command `:w`

**Comment by dantleech** [comment]
the diagnostics are executed on save only atm as they are (still) quite expensive, you can enable real time diagnostics with : https://phpactor.readthedocs.io/en/master/reference/configuration.html#language-server-diagnostics-on-update

it works for me:

![image](https://user-images.githubusercontent.com/530801/167291166-106b9c33-cded-41da-a55d-326683c4e424.png)

with the fake annotations:

![image](https://user-images.githubusercontent.com/530801/167291204-2bf830c2-b7ef-4b54-9b68-ac3df92aeaaf.png)

**Comment by KasparRosin** [comment]
Ok, yes.
The @method seems to work if it's defined in the current or any of the classes being extended.
For me, the problem currently came when i tried to read a method from an instance saved to a variable.

```php
class CompanyFactory extends Factory {
// ...
    return [ 'company' => $this->faker->company() ]
}
```

```php
abstract class Factory {
 /**                                                                                                                                                                                                      
  * The current Faker instance.                                                                                                                                                                           
  *                                                                                                                                                                                                       
  * @var \Faker\Generator                                                                                                                                                                                 
  */                                                                                                                                                                                                      
  protected $faker;  
 // ...
}
```

And now inside the Faker\Generator class there is the `@method company`

**Comment by KasparRosin** [comment]
Screenshots:
![image](https://user-images.githubusercontent.com/33309407/167344276-f3270a68-94a4-43ed-a1c5-2a8e94ce6415.png)
![image](https://user-images.githubusercontent.com/33309407/167344307-0fec1660-5da0-4b45-af8c-2a89410d9ca6.png)

**Comment by dantleech** [comment]
in a separate fix i found some issues with virtual methods fixed in #1564 can you try again?

**Comment by dantleech** [comment]
added another ticket to fix remaining issues: https://github.com/phpactor/phpactor/issues/1565

**Comment by KasparRosin** [comment]
Currently still having this issue with latest b704af6 commit

**Comment by KasparRosin** [comment]
> note that @property seems still not to be supported
To me, it seems that `@property` is supported? Or maybe i'm misunderstanding.
I'll dedicate some time later today, to write a test case that can hopefully reproduce this.

**Comment by dantleech** [comment]
I think this is now fixed (fixed remaining issues with property access I think - it was supproted, but not in all cases)
```
<?php

use Faker\Factory;

$faker = new Factory();
$faker = $faker->create();
$company = $faker->company; // string
$foo = $faker->iban('GB', 'asd');
$foo; // string
```

**Comment by KaranAhlawat** [comment]
Can we reopen this?
I am using phpactor with Emacs, and I still can't seem to get the autocompletion for virtual methods to work, and it also gives me warning that such a method does not exist.

![image](https://user-images.githubusercontent.com/56113511/219953281-69406a30-2c97-479c-8d25-8322bc2297ad.png)

![image](https://user-images.githubusercontent.com/56113511/219953367-2d1821c2-ddf1-4fe9-ae92-ec5b438a8ba5.png)
Defined on the Faker\Generator class.
