### ISSUE TITLE
[UseAdd] add an option to sort use statements

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#176]
Here is how I did it in VimL on another repo: https://github.com/arnaud-lb/vim-php-namespace/blob/ca40a1dabe4684ab7139bd056f0e6e7526f65392/plugin/phpns.vim#L181

Not sure you would want to do that vim-side though.

**Comment by dantleech** [comment]
This is more of a style fix, it may be that people don't want us to rudely mess up their diffs?

**Comment by greg0ire** [comment]
Hence the "option" part, this should clearly not be the default, but I do that everywhere and think a lot of people do so too. An option to do that from the start would be nice.

**Comment by dantleech** [comment]
Yeah, have currently been ignoring style fixes, as they can be applied with f.e. `phpcsfixer`. But maybe this would make sense (at the very least we could insert the use statement according to its alphabetic value).

For now we could do it in VimL. Eventually we could also either edit and replace the code from Phpactor (as with the current transformers) or provide a "change set" to apply to the code.

**Comment by sandermarechal** [comment]
> at the very least we could insert the use statement according to its alphabetic value
That would be great to start with. I take care to keep my use statements sorted alphabetically. It would be great if Phpactor at least inserts the new use statement in the correct position.

Sorting all use statements could be a separate refactoring IMHO.

**Comment by dantleech** [comment]
Oh, and importing classes is now done in PHP (as opposed to VimL). Relevant code is [here](https://github.com/phpactor/code-builder/blob/master/lib/Adapter/TolerantParser/TolerantUpdater.php#L91)

**Comment by greg0ire** [comment]
Not sure php-cs-fixer or phpcbf are able to work on part of a file… One thing in favor of delegating the work to them is the fact that you don't obtain the exact same result for if you use `:sort` or php-cs-fixer, because they don't agree on whether `\` is `< 'a'` or `> 'z'`
```
<php
use Foo\Bar\Baz;
use Foo\Bar;
```

**Comment by greg0ire** [comment]
Since it is php, I'm much more up to contributing it if you want. I would change the code so that it adds the new use statement before the first use statement that is lexicographically greater than the one to insert.

**Comment by dantleech** [comment]
Yeah, feel free to have a go :) Should be quite straight-forward, it will probably break test expectations outside of the package, but we can either accept that or add a flag to make it configurable if that were to make sense.

**Comment by dantleech** [comment]
Done!

**Comment by FatBoyXPC** [comment]
Did this get added as a vimrc option?

**Comment by greg0ire** [comment]
It's not optional. New statements are always added at the best possible place

**Comment by FatBoyXPC** [comment]
How is "best" determined? Alphabetically? By length? What if neither of those conventions exist?

**Comment by greg0ire** [comment]
Alphabetically. If the list is not sorted, it doesn't matter it still puts the statement before the first lexicographically superior statement

**Comment by greg0ire** [comment]
I would be OK with this as long as the current behavior stays the default, but I'd start a new issue if I were you.

**Comment by greg0ire** [comment]
Fixed the title :)

**Comment by dantleech** [comment]
Would still prefer a new issue tbh, less noise :)

**Comment by FatBoyXPC** [comment]
@dantleech new issue has been opened!

@greg0ire no option got added, I'd argue that the title is still incorrect :joy:

**Comment by greg0ire** [comment]
It's correct, it's just I did not end up implementing it that way :P
